// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Elders.Cronus.DomainModeling")]
[assembly: AssemblyDescriptionAttribute("Elders.Cronus.DomainModeling")]
[assembly: AssemblyProductAttribute("Elders.Cronus.DomainModeling")]
[assembly: AssemblyVersionAttribute("1.2.1")]
[assembly: AssemblyInformationalVersionAttribute("1.2.1")]
[assembly: AssemblyFileVersionAttribute("1.2.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.2.1";
    }
}
