using System;
using System.Threading;
using System.Threading.Tasks;

namespace Elders.Cronus;

/// <summary>
/// When we have a workflow which involves several aggregates it is recommended to have the whole process described
/// in a single place such as Saga/ProcessManager.
/// </summary>
public interface ISaga : IMessageHandler { }

/// <summary>
/// Message which will be published in the future.
/// </summary>
public interface IScheduledMessage : IMessage
{
    /// <summary>
    /// The date when this message will be published.
    /// </summary>
    DateTime PublishAt { get; }
}

/// <summary>
/// Defines a handler invoked when a previously scheduled saga timeout fires.
/// </summary>
/// <typeparam name="T">The scheduled message type that triggers the timeout.</typeparam>
public interface ISagaTimeoutHandler<in T> where T : IScheduledMessage
{
    /// <summary>
    /// Handles the specified saga timeout asynchronously.
    /// </summary>
    /// <param name="sagaTimeout">The scheduled message representing the timeout.</param>
    /// <param name="cancellationToken">A token to cancel the asynchronous operation.</param>
    /// <returns>A task that represents the asynchronous handle operation.</returns>
    Task HandleAsync(T sagaTimeout, CancellationToken cancellationToken = default);
}

/// <summary>
/// Base class for sagas / process managers. Provides command and timeout publishing helpers.
/// </summary>
public abstract class Saga : ISaga
{
    protected readonly IPublisher<ICommand> commandPublisher;
    protected readonly IPublisher<IScheduledMessage> timeoutRequestPublisher;

    /// <summary>
    /// Initializes a new <see cref="Saga"/>.
    /// </summary>
    /// <param name="commandPublisher">Publisher used to dispatch commands generated by the saga.</param>
    /// <param name="timeoutRequestPublisher">Publisher used to schedule saga timeouts.</param>
    public Saga(IPublisher<ICommand> commandPublisher, IPublisher<IScheduledMessage> timeoutRequestPublisher)
    {
        ArgumentNullException.ThrowIfNull(commandPublisher);
        ArgumentNullException.ThrowIfNull(timeoutRequestPublisher);
        this.commandPublisher = commandPublisher;
        this.timeoutRequestPublisher = timeoutRequestPublisher;
    }

    /// <summary>
    /// Schedules a timeout message to be re-delivered to the saga at <see cref="IScheduledMessage.PublishAt"/>.
    /// </summary>
    /// <typeparam name="T">The scheduled message type.</typeparam>
    /// <param name="timeoutMessage">The timeout message to schedule.</param>
    /// <param name="cancellationToken">A token to cancel the asynchronous operation.</param>
    /// <returns>A task that represents the asynchronous request operation.</returns>
    public Task RequestTimeoutAsync<T>(T timeoutMessage, CancellationToken cancellationToken = default) where T : IScheduledMessage
    {
        return timeoutRequestPublisher.PublishAsync(timeoutMessage, timeoutMessage.PublishAt, cancellationToken: cancellationToken);
    }
}
